#!/bin/bash


# 1. OS 확인
# uname + case 사용

case "$(uname -s)" in
    Linux*) dist = $(lsb_release -a | grep Distributor | awk -F" " '{print $3}')
    if [$dist == "Ubuntu"|"Debian"]; then
    
    ;;
    AIX*)

# 2. SSH 설정 파일 확인
# if [ -f ] 구문 사용

# 3. 설정 값 검색
# grep, awk로 값 추출

# 4. 값 비교 및 결과 출력
# if + echo 사용

# 5. 스크립트 종료
# exit 0