#!/bin/bash

OS=$(uname -s)

case "$OS" in
Linux)
OS="Linux"
;;
SunOS)
OS="Solaris"
;;
AIX)
OS="AIX"
;;
HP-UX)
OS="HP-UX"
;;
*)
OS="Unkown OS"
;;

esac

echo "OS is $OS"

if ps -ef | grep -v grep | grep -q "telnetd"; then
    echo "Telnet daemon is running."
if ps -ef | grep -v grep | grep -q "inetd"; then
    CONFIG_FILE="etc/inetd.conf"
    if [-f "$CONFIG_FILE"]; then
        

